///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesBg1 = 'assets/images/bg1.png';
  static const String screensForgotPassword = 'assets/screens/forgot_password.dart';
  static const String screensSigninScreen = 'assets/screens/signin_screen.dart';
  static const String screensSignupScreen = 'assets/screens/signup_screen.dart';
  static const String screensWelcomHome = 'assets/screens/welcom_home.dart';
  static const String screensWelcomScreen = 'assets/screens/welcom_screen.dart';

}
