name: logisync
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  blur: ^3.1.0
  csv: ^6.0.0
  data_table_2: ^2.5.11
  fl_chart: ^0.66.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_marker_cluster: ^1.3.4
  flutter_svg: ^2.0.10+1
  geolocator: ^11.0.0
  google_fonts: ^6.1.0
  latlong2: ^0.9.0
  material_design_icons_flutter: ^7.0.7296
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/icons/
